import { User, Role, Department, Document, DocumentType, Question, ExamAttempt } from '../types';

export const mockUsers: User[] = [
  { id: '1', name: 'Ahmad Isah Abubakar', email: 'aiabubakar2@cbn.gov.ng', role: Role.ADMIN, department: 'Development Finance Department' },
  { id: '2', name: 'Sabiu Abubakar', email: 'SABUBAKAR5@cbn.gov.ng', role: Role.STAFF, department: 'Development Finance Department' },
  { id: '3', name: 'Abubakar Lawan Gana', email: 'ALGANA@cbn.gov.ng', role: Role.STAFF, department: 'Research Department' },
  { id: '4', name: 'Muhammad Ibrahim', email: 'MIMUHAMMAD2@cbn.gov.ng', role: Role.STAFF, department: 'Human Resources Department' },
  { id: '5', name: 'Umar Ilyasu Balarabe', email: 'UBILYASU@cbn.gov.ng', role: Role.STAFF, department: 'Information Technology Department' },
  { id: '6', name: 'Idris Salihi Abdullahi', email: 'IASALIHI@cbn.gov.ng', role: Role.STAFF, department: 'Finance Department' },
];

interface Directorate {
  name: string;
  departments: Department[];
}

export const mockDirectorates: Directorate[] = [
    {
        name: "General",
        departments: [
            { id: 'general', name: 'General CBN Knowledge', description: 'Cross-cutting questions applicable to all staff members for general promotion exams.' },
        ]
    },
    {
        name: "Corporate Services Directorate",
        departments: [
            { id: 'ccd', name: 'Corporate Communications Department', description: 'Manages corporate communications and public relations.' },
            { id: 'hrd', name: 'Human Resources Department', description: 'Manages employee relations, recruitment, and development.' },
            { id: 'lsd', name: 'Legal Services Department', description: 'Provides legal counsel and services to the bank.' },
            { id: 'msd', name: 'Medical Services Department', description: 'Provides healthcare services to staff.' },
            { id: 'pssd', name: 'Procurement and Support Services Department', description: 'Manages procurement and general support services.' },
            { id: 'ssd', name: 'Security Services Department', description: 'Ensures the security of bank assets and personnel.' },
        ]
    },
    {
        name: "Governors' Directorate",
        departments: [
            { id: 'csd', name: 'Corporate Secretariat Department', description: 'Provides secretarial services to the Board and its Committees.' },
            { id: 'cd', name: 'Compliance Department', description: 'Ensures the bank complies with laws and regulations.' },
            { id: 'sdd', name: 'Special Duties Department', description: 'Handles special projects and assignments from the Governor.' },
            { id: 'iad', name: 'Internal Audit Department', description: 'Provides independent assurance on risk management.' },
            { id: 'rmd', name: 'Risk Management Department', description: 'Manages operational, financial, and strategic risks.' },
            { id: 'simd', name: 'Strategy & Innovation Management Department', description: 'Drives strategic planning and innovation initiatives.' },
        ]
    },
    {
        name: "Economic Policy Directorate",
        departments: [
            { id: 'fmd', name: 'Financial Markets Department', description: 'Manages domestic money and foreign exchange markets.' },
            { id: 'mpd', name: 'Monetary Policy Department', description: 'Formulates and implements monetary policy.' },
            { id: 'rd', name: 'Research Department', description: 'Conducts economic research and analysis.' },
            { id: 'remd', name: 'Reserve Management Department', description: 'Manages the nation\'s external reserves.' },
            { id: 'sd', name: 'Statistics Department', description: 'Collects, compiles, and disseminates economic data.' },
            { id: 'ted', name: 'Trade and Exchange Department', description: 'Manages trade and exchange control policies.' },
            { id: 'pspd', name: 'Payments System Policy Department', description: 'Develops policies for the national payments system.' },
        ]
    },
    {
        name: "Operations Directorate",
        departments: [
            { id: 'bsd_ops', name: 'Banking Services Department', description: 'Provides banking services to government and banks.' },
            { id: 'cobmd', name: 'Currency Operations and Branch Management Department', description: 'Manages currency issuance and branch operations.' },
            { id: 'fd', name: 'Finance Department', description: 'Manages the bank\'s finances and budget.' },
            { id: 'itd', name: 'Information Technology Department', description: 'Manages IT infrastructure and services.' },
        ]
    },
    {
        name: "Financial System Stability Directorate",
        departments: [
            { id: 'bsd_fss', name: 'Banking Supervision Department', description: 'Supervises and regulates banks and other financial institutions.' },
            { id: 'cpfid', name: 'Consumer Protection & Financial Inclusion Department', description: 'Protects consumers and promotes financial inclusion.' },
            { id: 'fprd', name: 'Financial Policy and Regulation Department', description: 'Develops regulatory policies for the financial sector.' },
            { id: 'ofisd', name: 'Other Financial Institutions Supervision Department', description: 'Supervises non-bank financial institutions.' },
            { id: 'pssd_fss', name: 'Payments System Supervision Department', description: 'Supervises the operations of the payments system.' },
            { id: 'dfisd', name: 'Development & Finance Institutions Supervision Department', description: 'Supervises development finance institutions.' },
        ]
    }
];

// Flattened list for components that need a simple array of all departments
export const mockDepartments: Department[] = mockDirectorates.flatMap(dir => dir.departments);


export const mockDocuments: Document[] = [
  { id: 'doc1', title: '2023 Prudential Guidelines', departmentId: 'bsd_fss', type: DocumentType.PDF, year: 2023, uploadedAt: '2023-10-15' },
  { id: 'doc2', title: 'Q3 2023 Economic Report', departmentId: 'rd', type: DocumentType.DOCX, year: 2023, uploadedAt: '2023-10-20' },
  { id: 'doc3', title: 'Agri-Business SME Investment Scheme (AGSMEIS) Framework', departmentId: 'dfisd', type: DocumentType.PDF, year: 2022, uploadedAt: '2022-05-10' },
  { id: 'doc4', title: 'AML/CFT Regulations', departmentId: 'bsd_fss', type: DocumentType.PDF, year: 2022, uploadedAt: '2022-11-01' },
  { id: 'doc5', title: 'Presentation on Monetary Policy', departmentId: 'mpd', type: DocumentType.PPTX, year: 2024, uploadedAt: '2024-02-28' },
  { id: 'doc6', title: 'Cybersecurity Framework for Banks', departmentId: 'pssd_fss', type: DocumentType.PDF, year: 2023, uploadedAt: '2023-08-19' },
  { id: 'doc7', title: 'Operational Risk Management Guide', departmentId: 'rmd', type: DocumentType.DOCX, year: 2024, uploadedAt: '2024-01-05' },
];

export const mockQuestions: Question[] = [
    { id: 'q1', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'A software application used to provide access to documents for boardroom meetings is called:', options: ['BoardBook', 'DocuVault', 'MeetingShelf', 'Diligent Board'], correctAnswer: 'Diligent Board' },
    { id: 'q2', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'What is Single Obligor?', options: ['A customer with only one loan facility', 'The total credit exposure to one borrower or related parties', 'A bank segment for single-account holders', 'A simplified loan package'], correctAnswer: 'The total credit exposure to one borrower or related parties' },
    { id: 'q3', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'A super-agent with maximum shareholders\' funds must write to CBN for approval when the fund exceeds:', options: ['₦25 million', '₦50 million', '₦100 million', '₦200 million'], correctAnswer: '₦100 million' },
    { id: 'q4', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'What is Currency Indent?', options: ['Internal memo for cash allocation', 'CBN request for fresh currency from Mint', 'Monthly vault balance summary', 'A vault audit report'], correctAnswer: 'CBN request for fresh currency from Mint' },
    { id: 'q5', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following is NOT part of a bank\'s strategy?', options: ['Digital transformation', 'Branch security protocols', 'Customer growth initiatives', 'Product/service diversification'], correctAnswer: 'Branch security protocols' },
    { id: 'q6', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which is NOT part of the CBN statement of financial account?', options: ['Currency in circulation', 'External reserves', 'Vault cash of DMBs', 'Consumer credit index'], correctAnswer: 'Consumer credit index' },
    { id: 'q7', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'What does a compliance audit measure?', options: ['Staff productivity', 'Profit margins', 'Adherence to laws and internal policies', 'Market share performance'], correctAnswer: 'Adherence to laws and internal policies' },
    { id: 'q8', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which is NOT a stakeholder in the National Financial Literacy Framework?', options: ['DMBs', 'NAICOM', 'CBN', 'Nigerian Bar Association'], correctAnswer: 'Nigerian Bar Association' },
    { id: 'q9', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Agency for illicit-drug control in Nigeria:', options: ['NDIC', 'EFCC', 'NAFDAC', 'NDLEA'], correctAnswer: 'NDLEA' },
    { id: 'q10', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Current Payment System Strategic Roadmap is for which year?', options: ['2025', '2027', '2028', '2030'], correctAnswer: '2025' },
    { id: 'q11', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Full meaning of USSD:', options: ['Unified Secure Service Data', 'Unstructured Supplementary Service Data', 'User Session Shortcode Dialling', 'Universal Secure Session Device'], correctAnswer: 'Unstructured Supplementary Service Data' },
    { id: 'q12', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Appraisal of Board of Directors for FIs is done:', options: ['Monthly', 'Bi-annually', 'Annually', 'Every two years'], correctAnswer: 'Annually' },
    { id: 'q13', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Offences constituting misconduct that could lead to termination include:', options: ['Misappropriation of funds', 'Malingering', 'Informal dress code breach', 'Minor system login delay'], correctAnswer: 'Malingering' },
    { id: 'q14', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which index is used to calculate inflation?', options: ['Consumer Price Index (CPI)', 'Producer Price Index (PPI)', 'Retail Price Trend', 'GDP Deflator'], correctAnswer: 'Consumer Price Index (CPI)' },
    { id: 'q15', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Tenure for Independent Non-Executive Directors is:', options: ['3 years, renewable twice', '4 years, renewable twice', '5 years non-renewable', '6 years with review'], correctAnswer: '4 years, renewable twice' },
    { id: 'q16', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Condition for unconfirmed staff maternity leave:', options: ['No payment', 'Full pay for 112 days', 'Confirmation after maternity leave and then pay', 'Optional leave for probationers'], correctAnswer: 'No payment' },
    { id: 'q17', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'CBN vault is classified into the following EXCEPT:', options: ['Active vault', 'Transit vault', 'Nostro vault', 'Static vault'], correctAnswer: 'Nostro vault' },
    { id: 'q18', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Reconciliation of account is a form of:', options: ['Detective control', 'Preventive control', 'Directive control', 'Corrective control'], correctAnswer: 'Detective control' },
    { id: 'q19', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Initiative to foster paperless culture — Docflow is a:', options: ['Compliance tool', 'Digital document tracking system', 'Audit feature', 'Email encryption service'], correctAnswer: 'Digital document tracking system' },
    { id: 'q20', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'What is Stagflation?', options: ['High growth, low inflation', 'Low growth with high inflation', 'Deflationary economy', 'Moderate growth and inflation'], correctAnswer: 'Low growth with high inflation' },
    { id: 'q21', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'If PMI is less than 50, it indicates:', options: ['Expansion', 'Peak', 'Contraction', 'Stability'], correctAnswer: 'Contraction' },
    { id: 'q22', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Maximum number of times a cheque can be presented is:', options: ['Twice', 'Three times', 'Four times', 'Once only'], correctAnswer: 'Three times' },
    { id: 'q23', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'How many days\' notice should a director give before resignation?', options: ['7 days', '30 days', '28 days', '90 days'], correctAnswer: '90 days' },
    { id: 'q24', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'What is compliance used for?', options: ['Profit maximization', 'Ensuring regulatory adherence', 'Market expansion', 'Customer satisfaction tracking'], correctAnswer: 'Ensuring regulatory adherence' },
    { id: 'q25', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Meaning of Information Security Management System:', options: ['Network firewall setup', 'Framework to manage IT security', 'Data backup schedule', 'Antivirus update program'], correctAnswer: 'Framework to manage IT security' },
    { id: 'q26', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The primary physical protection of laptops is:', options: ['Password lock screen', 'Security cable lock', 'BIOS encryption', 'VPN connection'], correctAnswer: 'Security cable lock' },
    { id: 'q27', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Quorum for MPC (Monetary Policy Committee) is:', options: ['7 members', '9 members', '6 members', '5 members'], correctAnswer: '6 members' },
    { id: 'q28', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Maximum number of extended family members on a board is:', options: ['2', '3', '4', '5'], correctAnswer: '2' },
    { id: 'q29', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'BDC reports to CBN are submitted how often?', options: ['Daily', 'Weekly', 'Monthly', 'Quarterly'], correctAnswer: 'Daily' },
    { id: 'q30', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The most commonly used physical deterrence is:', options: ['CCTV cameras', 'Security guards', 'Perimeter Fencing', 'Access cards'], correctAnswer: 'Security guards' },
    { id: 'q31', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Minimum capital requirement for State PMBs is:', options: ['₦8 Billion', '₦5 Billion', '₦2.5 Billion', '₦1 billion'], correctAnswer: '₦8 Billion' },
    { id: 'q32', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which is NOT part of the payment system functions breakdown?', options: ['Clearing', 'Payment initiation', 'Loan disbursement', 'Settlement'], correctAnswer: 'Loan disbursement' },
    { id: 'q33', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Tier 2 wallet — Daily & cumulative limit:', options: ['₦50,000/day; ₦300,000 cumulative', '₦200,000/day; ₦500,000 cumulative', '₦200,000/day; ₦1 million cumulative', '₦500,000/day; ₦2 million cumulative'], correctAnswer: '₦200,000/day; ₦500,000 cumulative' },
    { id: 'q34', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Requirements for posting on social media (from CCD):', options: ['Prior unit head approval', 'Schedule via marketing only', 'Use personal accounts', 'No approval needed'], correctAnswer: 'Prior unit head approval' },
    { id: 'q35', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Brand image — correct font size for body is:', options: ['8pt', '10pt', '12pt', '14pt'], correctAnswer: '12pt' },
    { id: 'q36', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Head Currency Museum is called:', options: ['CBN Museum Curator', 'Head Numismatic Department', 'Chief Currency Historian', 'Currency Vault Manager'], correctAnswer: 'Head Numismatic Department' },
    { id: 'q37', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The following are functions of facility managers EXCEPT:', options: ['Property maintenance', 'Lunch menu planning', 'Security oversight', 'Vendor coordination'], correctAnswer: 'Lunch menu planning' },
    { id: 'q38', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'If currency depreciates, what happens to Foreign Asset Revaluation Account?', options: ['Falls in value', 'Remains unchanged', 'Increases in value', 'Written off entirely'], correctAnswer: 'Increases in value' },
    { id: 'q39', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'An increase in cash reserve ratio does what to liquidity?', options: ['Increases liquidity', 'Decreases liquidity', 'No effect', 'Doubles liquidity'], correctAnswer: 'Decreases liquidity' },
    { id: 'q40', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'CBN interventions interest rate is:', options: ['9 %', '12 %', '15 %', '7 %'], correctAnswer: '9 %' },
    { id: 'q41', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following constitutes an infraction for Bureau De Change (BDC) operators under CBN regulations?', options: ['Failure to remit foreign-exchange proceeds to CBN within stipulated time', 'Displaying approved exchange rates at premises', 'Offering rates within approved margin', 'Operating only on weekdays'], correctAnswer: 'Failure to remit foreign-exchange proceeds to CBN within stipulated time' },
    { id: 'q42', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Standing Deposit Facility is remunerated at:', options: ['3 %', '–1 %', '2 %', '5 %'], correctAnswer: '–1 %' },
    { id: 'q43', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Meaning & use of Standing Lending Facility:', options: ['Facility against securities for overnight liquidity', 'Term loans for SMEs', 'Short-term marketing funds', 'Staff salary advances'], correctAnswer: 'Facility against securities for overnight liquidity' },
    { id: 'q44', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'What organ does hypertension affect most?', options: ['Lungs', 'Pancreas', 'Kidneys', 'Liver'], correctAnswer: 'Kidneys' },
    { id: 'q45', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'USSD full meaning:', options: ['User System Secure Dial', 'Unstructured Supplementary Service Data', 'Universal Service Short Data', 'Unified Security Session Detail'], correctAnswer: 'Unstructured Supplementary Service Data' },
    { id: 'q46', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which is NOT a member of the CBN Board of Directors?', options: ['Deputy Governor, Financial System Stability', 'Permanent Secretary, Federal Ministry of Finance', 'Minister of Finance', 'Accountant-General of the Federation'], correctAnswer: 'Accountant-General of the Federation' },
    { id: 'q47', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Recovery Time Objective is the interval between:', options: ['Disruption notice & mitigation start', 'Disaster occurrence & normal-service restoration', 'Objective set & its achievement', 'Critical-service failure & BCP invocation'], correctAnswer: 'Disaster occurrence & normal-service restoration' },
    { id: 'q48', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Vault categorisation in CBN branches EXCLUDES:', options: ['Local Currency', 'Foreign Currency', 'Security items', 'Coins'], correctAnswer: 'Security items' },
    { id: 'q49', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Most commonly used physical deterrent:', options: ['Fencing', 'Locks', 'CCTV', 'Security guards'], correctAnswer: 'Security guards' },
    { id: 'q50', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'A muster point is:', options: ['Treatment room in an emergency', 'Staff convergence & accounting point', 'Escape-only point', 'Discussion point for procedures'], correctAnswer: 'Staff convergence & accounting point' },
    { id: 'q51', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'MSMEDF portion earmarked for women entrepreneurs:', options: ['60 %', '10 %', '30 %', '50 %'], correctAnswer: '50 %' },
    { id: 'q52', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which is NOT a financial-system regulator?', options: ['NDIC', 'SEC', 'PENCOM', 'NCC'], correctAnswer: 'Nigerian Bar Association' },
    { id: 'q53', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Primary RTGS characteristic:', options: ['Batch settlement', 'Real-time individual settlement', 'End-of-day settlement', 'International-only'], correctAnswer: 'Real-time individual settlement' },
    { id: 'q54', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Inflation rises 2 % → 5 %; who benefits?', options: ['Savers', 'Borrowers', 'Exporters', 'Workers'], correctAnswer: 'Borrowers' },
    { id: 'q55', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Maximum MSMEDF micro-enterprise loan:', options: ['₦500 000', '₦250 000', '₦5 000 000', '₦1 000 000'], correctAnswer: '₦1 000 000' },
    { id: 'q56', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Interlocking directorship limit in a financial holding company:', options: ['Two', 'Three', 'Four', 'Five'], correctAnswer: 'Two' },
    { id: 'q57', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which is NOT a development-finance institution?', options: ['Bank of Industry', 'Development Bank of Nigeria', 'NIRSAL Microfinance Bank', 'Bank of Agriculture'], correctAnswer: 'Bank of Agriculture' },
    { id: 'q58', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'CBN strategic theme EXCEPT:', options: ['Price Stability & Monetary Policy Effectiveness', 'Robust & Refocused Financial System', 'Excellence in Central Banking Operations', 'Robust & Resilient Financial System'], correctAnswer: 'Robust & Resilient Financial System' },
    { id: 'q59', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Full meaning of USSD:', options: ['Unsupported Script-less Service Data', 'Unstructured Script-less Service Data', 'Unsupported Supplementary Service Data', 'Unstructured Supplementary Service Data'], correctAnswer: 'Unstructured Supplementary Service Data' },
    { id: 'q60', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Minimum capital/risk-weighted-assets ratio for finance companies:', options: ['13.0 %', '10.0 %', '12.5 %', '15 %'], correctAnswer: '10.0 %' },
    { id: 'q61', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which is NOT normally in Nigeria’s foreign-reserve stock?', options: ['Euro', 'Chinese Yuan', 'Great Britain Pound', 'Swiss Franc'], correctAnswer: 'Swiss Franc' },
    { id: 'q62', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Balanced scorecard improves focus by:', options: ['Automating dashboards', 'Linking strategy to multi-perspective outcomes', 'Limiting review frequency', 'Financial-data-only focus'], correctAnswer: 'Linking strategy to multi-perspective outcomes' },
    { id: 'q63', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Post-Project-Rise, OFiSC became:', options: ['Development Finance Dept', 'Development & FI Supervision Dept', 'Development-Finance Intervention Supervision Dept', 'Development & Finance Institutions Supervision Dept'], correctAnswer: 'Development & Finance Institutions Supervision Dept' },
    { id: 'q64', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which is NOT perimeter-security equipment?', options: ['Badges', 'Smart-cards', 'Locks', 'Lighting'], correctAnswer: 'Lighting' },
    { id: 'q65', departmentId: 'general', topic: 'General CBN Knowledge', questionText: '17-year-old with blurry vision given corrective lenses; true statement:', options: ['Vision improved forever, no more lenses needed', 'Lenses raise eye-pressure', 'Vision improved while lenses are worn', 'Lenses show intelligence'], correctAnswer: 'Vision improved while lenses are worn' },
    { id: 'q66', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Super-agents must disclose controllers of > … % share capital:', options: ['5', '17', '10', '15'], correctAnswer: '10' },
    { id: 'q67', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Statutory FX reports to FIFX are submitted:', options: ['Daily & Monthly', 'Daily, Weekly & Monthly', 'Weekly, Monthly & Quarterly', 'All of the above'], correctAnswer: 'All of the above' },
    { id: 'q68', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Stagflation is:', options: ['High inflation + high unemployment', 'Low inflation + high growth', 'Deflation + recession', 'Low inflation + low unemployment'], correctAnswer: 'High inflation + high unemployment' },
    { id: 'q69', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Velocity of money (MV=PQ): M=₦4 tr, P=2, Q=₦10 tr → V=', options: ['1', '2', '2.5', '5'], correctAnswer: '5' },
    { id: 'q70', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which export form is NOT used?', options: ['NCX', 'Form M', 'NXP', 'None of the above'], correctAnswer: 'NXP' },
    { id: 'q71', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Predominant CBN intervention interest rate:', options: ['10 %', '9 %', '8 %', '7 %'], correctAnswer: '9 %' },
    { id: 'q72', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'IMTO rate-quote band must be within:', options: ['±1.5 %', '±2.0 %', '±2.5 %', 'None'], correctAnswer: 'None' },
    { id: 'q73', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Phishing best described as:', options: ['Malware disrupting PC', 'Social-engineering data theft', 'Denial-of-service', 'SQL-injection'], correctAnswer: 'Social-engineering data theft' },
    { id: 'q74', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Minimum capital for payment-solution-services entity:', options: ['₦250 m', '₦100 m', '₦2 bn', '₦50 m'], correctAnswer: '₦100 m' },
    { id: 'q75', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Document sent to units for budget proposals:', options: ['Budget enquiry', 'Call circular', 'Budget letter', 'Call letter'], correctAnswer: 'Budget letter' },
    { id: 'q76', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'NOT a physical-security control category:', options: ['Deterrence & delaying', 'Response & detection', 'Assessment & detection', 'Delaying & lighting'], correctAnswer: 'Delaying & lighting' },
    { id: 'q77', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Vaccine-preventable EXCEPT:', options: ['Hepatitis C', 'Diphtheria', 'Hepatitis B', 'Tetanus'], correctAnswer: 'Hepatitis C' },
    { id: 'q78', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'BIS defines payment systems as set of … ensuring money circulation:', options: ['Information', 'Instruments', 'Regulations', 'Instructions'], correctAnswer: 'Instruments' },
    { id: 'q79', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Hinders performance management:', options: ['Timely reviews', 'Aligned metrics', 'Ambiguous goals', 'Clear KPIs'], correctAnswer: 'Ambiguous goals' },
    { id: 'q80', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Futures differ from forwards EXCEPT:', options: ['Margins', 'Mark-to-market', 'Exchange-traded', 'Fixing future asset prices'], correctAnswer: 'Fixing future asset prices' },
    { id: 'q81', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Licensed bank in Nigeria = …', options: ['CBN-owned', 'Unregistered operator', 'CBN-approved', 'Finance-Ministry-managed'], correctAnswer: 'CBN-approved' },
    { id: 'q82', departmentId: 'general', topic: 'General CBN Knowledge', questionText: '“Disruptive technology” means:', options: ['Incremental process enhancement', 'Hard-to-implement tech', 'Alters/replaces existing practices', 'Niche-market only'], correctAnswer: 'Alters/replaces existing practices' },
    { id: 'q83', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'NOT a consumer-protection principle:', options: ['Transparency', 'Fair treatment', 'Arbitrary decision-making', 'Complaint handling'], correctAnswer: 'Arbitrary decision-making' },
    { id: 'q84', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Naira depreciation vs USD → CBN Foreign-Asset Revaluation Account:', options: ['USD reserves cease', 'Increases', 'Decreases', 'USD reserves fall'], correctAnswer: 'Decreases' },
    { id: 'q85', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'NOT needed pre-audit:', options: ['Review last issues', 'Perform substantive tests', 'Letter of Authority', 'Risk Assessment'], correctAnswer: 'Risk Assessment' },
    { id: 'q86', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Tier-2 mobile-money limits (daily; cumulative):', options: ['200 k; 350 k', '50 k; 300 k', '200 k; 500 k', '500 k; Unlimited'], correctAnswer: '200 k; 500 k' },
    { id: 'q87', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Super-agent disclosure threshold: ≥ … % capital or significant influence:', options: ['5', '10', '3', '20'], correctAnswer: '10' },
    { id: 'q88', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Key benefit of Service-Oriented Architecture:', options: ['Less complexity', 'Better interoperability', 'Lower security need', 'None'], correctAnswer: 'Better interoperability' },
    { id: 'q89', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Good financial habit:', options: ['Spend all income', 'Save regularly', 'Ignore statements', 'Use cash only'], correctAnswer: 'Save regularly' },
    { id: 'q90', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Portfolio excess 5 bp, benchmark 4 bp → portfolio return:', options: ['20 bp', '8 bp', '9 bp', '1 bp'], correctAnswer: '1 bp' },
    { id: 'q91', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'ISMS main objective:', options: ['Staff productivity', 'CIA of data', 'Monitor staff', 'Block external links'], correctAnswer: 'CIA of data' },
    { id: 'q92', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Liquidity tranche purpose:', options: ['10-y yield max', 'Fund capital projects', 'Buy real estate', 'Instant payment access'], correctAnswer: 'Instant payment access' },
    { id: 'q93', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'MCTC composition:', options: ['2 DGs + 5 Dirs', '1 DG + 6 Dirs', '1 DG + 9 Dirs', '1 DG + 2 NED + 4 Dirs'], correctAnswer: 'One DG, two Non-Executive Directors and four Departmental Directors' },
    { id: 'q94', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Social-media policy communication must be:', options: ['Team-lead preference', 'Trending-topic driven', 'Opposition-frequency based', 'Strategy-aligned content/timing/tone/audience'], correctAnswer: 'Strategy-aligned content/timing/tone/audience' },
    { id: 'q95', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Crowding-out effect: gov’t borrowing …', options: ['Raises public spend, lowers inflation expectations', 'Raises rates, cuts private invest', 'Lowers revenue', 'None'], correctAnswer: 'Raises rates, cuts private invest' },
    { id: 'q96', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'NOT a composite risk rating:', options: ['Medium', 'Low', 'High', 'Above Average'], correctAnswer: 'Above Average' },
    { id: 'q97', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The Naira is a legal tender because:', options: ['It is widely accepted in Nigeria', 'It has the backing of the law', 'Counterfeit naira can easily be detected', 'It is used in Nigeria'], correctAnswer: 'It has the backing of the law' },
    { id: 'q98', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following is NOT true about the Act phase of delivery milestones in respect of ISO 41001:2018 Facilities Management in CBN?', options: ['Corrective Actions', 'Management Review', 'Pre-certification Audit Support', 'None of the above'], correctAnswer: 'None of the above' },
    { id: 'q99', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The chronological list of all accounts in the general ledger arranged by category with clear descriptions and qualifiers is called:', options: ['Listing of accounts', 'Chart of accounts', 'Mapping of accounts', 'Trial Balance'], correctAnswer: 'Chart of accounts' },
    { id: 'q100', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'One of the following is NOT a reserve currency:', options: ['Bitcoin', 'US Dollar', 'Euro', 'Renminbi'], correctAnswer: 'Bitcoin' },
    { id: 'q101', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Physical security deals with all of the following EXCEPT:', options: ['Buildings', 'Logical systems', 'Computer Rooms', 'Computer devices'], correctAnswer: 'Logical systems' },
    { id: 'q102', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following risks is associated with cyber-attacks or outdated computer systems?', options: ['Credit Risk', 'Market Risk', 'Information Technology risk', 'Liquidity Risk'], correctAnswer: 'Information Technology risk' },
    { id: 'q103', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following contributes MOST directly to deepening financial inclusion?', options: ['Enforcing customer due diligence', 'Developing mobile savings products', 'Auditing commercial banks', 'Launching AML/CFT solutions'], correctAnswer: 'Developing mobile savings products' },
    { id: 'q104', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The administration of injections/medications to prevent some infectious diseases in children is called:', options: ['Counselling', 'Vaccination', 'Physiotherapy', 'Scanning and polishing'], correctAnswer: 'Vaccination' },
    { id: 'q105', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which tool is used in Enterprise Portfolio Management to assess initiative value?', options: ['Fishbone diagram', 'Gantt chart', 'Business case', 'SWOT'], correctAnswer: 'Business case' },
    { id: 'q106', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'What is the key consideration in whistleblowing?', options: ['Avenging wrongs among colleagues', 'Leadership', 'Confidentiality', 'Empowering'], correctAnswer: 'Confidentiality' },
    { id: 'q107', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The CBN has set a daily withdrawal and weekly cumulative withdrawal limit on PoS terminals respectively per customer to ₦... and ₦...', options: ['₦100,000 and ₦500,000', '₦150,000 and ₦500,000', '₦50,000 and ₦350,000', '₦150,000 and ₦750,000'], correctAnswer: '₦150,000 and ₦500,000' },
    { id: 'q108', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'A merchant bank entered into repo agreement with a commercial bank, for settlement on T+4. This type of repo is called:', options: ['Vertical Repo', 'Horizontal Repo', 'Crossing Repo', 'Reversed Repo'], correctAnswer: 'Vertical Repo' },
    { id: 'q109', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following is the ABSOLUTE FIRST requirement of computer security?', options: ['Password policy', 'Application security', 'Logical security', 'Physical security'], correctAnswer: 'Physical security' },
    { id: 'q110', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The methodology adapted by CBN for its Strategy Execution is:', options: ['The Kaplan/Norton Balanced Scorecard Framework', 'The Open Group Architecture Framework', 'Ishikawa Framework', 'None of the above'], correctAnswer: 'The Kaplan/Norton Balanced Scorecard Framework' },
    { id: 'q111', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'BMatch in Nigeria\'s forex market refers to:', options: ['A platform for autonomous forex trading', 'A cryptocurrency exchange', 'A fuel subsidy program', 'A GDP calculation tool'], correctAnswer: 'A platform for autonomous forex trading' },
    { id: 'q112', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The Non-resident Nigerian Ordinary Account was introduced to enable non-resident Nigerians:', options: ['Access loans in Nigeria for business', 'Get good foreign exchange rates', 'Prepare adequately for retirement', 'Remit their foreign earnings to Nigeria and manage funds in both foreign and local currency'], correctAnswer: 'Remit their foreign earnings to Nigeria and manage funds in both foreign and local currency' },
    { id: 'q113', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'A bond typically has a maturity of:', options: ['Less than 91 days', '1 month', '1 to 30 years', '1 to 7 days'], correctAnswer: '1 to 30 years' },
    { id: 'q114', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'During a crisis of misinformation, what is the most appropriate sequence of response process to follow?', options: ['Contact influencers to correct the narrative and issue timely clarification', 'Issue timely clarification, escalate for approval and draft a rebuttal based on facts and institutional voice', 'Draft a rebuttal based on facts and institutional voice, escalate for approval, and issue timely clarification', 'Draft a rebuttal based on facts and institutional voice, issue timely clarification and escalate for approval'], correctAnswer: 'Draft a rebuttal based on facts and institutional voice, escalate for approval, and issue timely clarification' },
    { id: 'q115', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Complaints by CBN staff can be treated by the Public Complaints Office if they meet the following conditions, EXCEPT:', options: ['The staff complainant must have exhausted all departmental and HR procedures', 'The staff had cogent reasons for dissatisfaction with HR and departmental processes', 'The staff has cogent reasons for dissatisfaction with decisions of the Committee of Governors and Board', 'If the complaint is anonymous'], correctAnswer: 'If the complaint is anonymous' },
    { id: 'q116', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following is NOT a composite risk rating under risk-based supervision?', options: ['Medium', 'Low', 'High', 'Above Average'], correctAnswer: 'Above Average' },
    { id: 'q117', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'If quantity of money = ₦9 million and velocity = 3, nominal GDP is:', options: ['₦12 million', '₦3 million', '₦27 million', '₦6 million'], correctAnswer: '₦6 million' },
    { id: 'q118', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following is a scheme that has a component to instill credit discipline in borrowers for facilities extended by banks?', options: ['Agricultural Credit Guarantee Scheme Fund (ACGSF)', 'Non-Oil Export Stimulation Facility (NES)', 'Real Sector Support Facility (RSSF)', 'Micro, Small and Medium Enterprises Development Fund (MSMEDF)'], correctAnswer: 'Micro, Small and Medium Enterprises Development Fund (MSMEDF)' },
    { id: 'q119', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'All the following are focus areas of CBN Corporate Social Responsibility EXCEPT:', options: ['Digital Inclusion', 'Environmental Sustainability', 'Disaster Relief', 'Investment Banking'], correctAnswer: 'Investment Banking' },
    { id: 'q120', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'A mutilated note is expected, among other conditions, to be at least:', options: ['½ of the original size', '¾ of the original size', '¼ of the original size', '⅓ of the original size'], correctAnswer: 'Settling international obligations' },
    { id: 'q121', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'In the COBEC, harassment constitutes:', options: ['Misconduct', 'Marginal misconduct', 'Gross misconduct', 'Grave misconduct'], correctAnswer: 'Grave misconduct' },
    { id: 'q122', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following can be considered a demand management policy?', options: ['Fiscal policy only', 'Fiscal and monetary policy', 'Structural policy', 'Expenditure switching policy'], correctAnswer: 'Fiscal and monetary policy' },
    { id: 'q123', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'A yield curve shows:', options: ['Company profit forecasts', 'Interest rates across maturities', 'Stock exchange trends', 'Inflation forecasts'], correctAnswer: 'Interest rates across maturities' },
    { id: 'q124', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'What is a common reason for the CBN to revoke the licence of a microfinance bank?', options: ['Offering a digital product', 'Failure to comply with BOFIA 2020 regulations', 'Offering high-interest savings accounts', 'Merging with a commercial bank'], correctAnswer: 'Failure to comply with BOFIA 2020 regulations' },
    { id: 'q125', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following statements is correct about female staff members who have been employed for less than 12 months?', options: ['Not eligible for maternity leave', 'Eligible for maternity leave without salary only', 'Eligible for maternity leave with half salary only', 'Eligible for maternity leave allowance'], correctAnswer: 'Eligible for maternity leave without salary only' },
    { id: 'q126', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The foreign reserves are crucial for:', options: ['Paying domestic salaries', 'Financing domestic activities', 'Settling international obligations', 'Distributing social grants'], correctAnswer: 'Settling international obligations' },
    { id: 'q127', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following is NOT a multilateral financial institution?', options: ['The World Bank', 'European Central Bank', 'International Monetary Fund', 'Asian Development Bank'], correctAnswer: 'Asian Development Bank' },
    { id: 'q128', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The record of a country\'s transactions in goods, services and... is referred to as... while the difference between merchandise exports and merchandise imports is referred to as...', options: ['Capital account, current account', 'Current account; trade balance', 'Balance of payments; trade balance', 'Balance of payments; capital account'], correctAnswer: 'Balance of payments; trade balance' },
    { id: 'q129', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'In the CBN\'s Performance Management System, what is the most critical factor in setting SMART objectives?', options: ['Ensuring objectives are easily achievable', 'Linking objectives to operational and/or strategic goals', 'Allowing employees to set their own targets and constant feedback', 'Focusing only on quantitative measures'], correctAnswer: 'Linking objectives to operational and/or strategic goals' },
    { id: 'q130', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The main objective of an audit opinion is to provide... that the statements are free from material misstatement.', options: ['Full assurance', 'Guarantee', 'Reasonable assurance', 'Unqualified opinion'], correctAnswer: 'Reasonable assurance' },
    { id: 'q131', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'What percentage of the MSMEDF fund is allocated for women?', options: ['30%', '40%', '50%', '60%'], correctAnswer: '40%' },
    { id: 'q132', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The two factors used in moderating the ratings assigned to overall net risk in the Composite Risk Rating for banks are:', options: ['Capital and Liquidity', 'Risk Identification and Risk Assessment', 'Capital and Earnings', 'Capital and Gross Profit'], correctAnswer: 'Capital and Liquidity' },
    { id: 'q133', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'In accordance with the Records Management Policy, records in their semi-active stage must be:', options: ['Disposed', 'Scanned and archived', 'Scanned and destroyed', 'Scanned and transferred to the Records Centre'], correctAnswer: 'Scanned and transferred to the Records Centre' },
    { id: 'q134', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'As a Deputy Project Manager, your team member informed you that the product delivered to the customer five days ago has a defect and should be recalled. What should you do?', options: ['Inform the project manager immediately', 'Send for the defective item to avoid customer loss', 'Carry out the review of quality checklist', 'None of the above'], correctAnswer: 'Inform the project manager immediately' },
    { id: 'q135', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of these is NOT a methodology for measuring credit risk under Basel II?', options: ['Basic Indicator Approach', 'Advanced Measurement Approach', 'Internal Model Approach', 'Internal Ratings Based Approach'], correctAnswer: 'Internal Ratings Based Approach' },
    { id: 'q136', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The highest decision-making body of the Bank is:', options: ['The Committee of Departmental Directors', 'The Board of Directors', 'The Governors Consultative Committee', 'The Committee of Governors'], correctAnswer: 'The Board of Directors' },
    { id: 'q137', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which currency is the most traded in the world?', options: ['British Pound', 'Euro', 'Saudi Riyal', 'US Dollar'], correctAnswer: 'US Dollar' },
    { id: 'q138', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'What is a mantrap?', options: ['A trusted security domain', 'A mechanism for logical access control', 'A double-door room used for physical access control', 'A device for fire suppression'], correctAnswer: 'A double-door room used for physical access control' },
    { id: 'q139', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The appraisal of the Board of Directors of a Financial Institution and its Committees shall be done:', options: ['Monthly', 'Quarterly', 'Semi-annually', 'Annually'], correctAnswer: 'Annually' },
    { id: 'q140', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following end organs is most commonly damaged by uncontrolled hypertension?', options: ['Liver', 'Kidneys', 'Lungs', 'Pancreas'], correctAnswer: 'Kidneys' },
    { id: 'q141', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Standing Deposit Facility is currently remunerated at an interest rate of:', options: ['MPR +50 basis points', 'MPR +100 basis points', 'MPR –100 basis points', 'MPR +500 basis points'], correctAnswer: 'MPR –100 basis points' },
    { id: 'q142', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'A director is required to submit a written notice of resignation addressed to the Chairman of the board... days before the effective date of resignation.', options: ['20', '30', '60', '90'], correctAnswer: '30' },
    { id: 'q143', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'All of the following are licensed Payment Service Providers EXCEPT:', options: ['Commercial Bank', 'Mobile Money Operators', 'Payment Solution Service Providers', 'Payment Terminal Solution Providers'], correctAnswer: 'Payment Terminal Solution Providers' },
    { id: 'q144', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following are part of activities done during the healthy lifestyle programme?', options: ['Exercise', 'Lecture presentations', 'Measurement of weight and height', 'All of the above'], correctAnswer: 'All of the above' },
    { id: 'q145', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Microfinance Certification by the Chartered Institute of Bankers of Nigeria is a CBN requirement for the appointment of:', options: ['Managing Director only', 'All directors', 'Non-Executive Directors', 'Managing Director and Management staff'], correctAnswer: 'Managing Director and Management staff' },
    { id: 'q146', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'The instrument used for the measurement of blood pressure is called:', options: ['Thermometer', 'Weighing Scale', 'ECG machine', 'Sphygmomanometer'], correctAnswer: 'Sphygmomanometer' },
    { id: 'q147', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'According to the CBN Act 2007, the Bank shall within... months after the close of each financial year transmit to the National Assembly and to the President a copy of its annual accounts certified by the Auditors.', options: ['One', 'Three', 'Two', 'Four'], correctAnswer: 'Two' },
    { id: 'q148', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Which of the following is NOT covered by the facilities management function in CBN?', options: ['Planned preventive maintenance', 'Project planning implementation management', 'Facility repair', 'Office space management'], correctAnswer: 'Project planning implementation management' },
    { id: 'q149', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Sukuk differs from conventional bonds by:', options: ['Being tax-free', 'Being only for men', 'Not involving interest', 'Being short term'], correctAnswer: 'Not involving interest' },
    { id: 'q150', departmentId: 'general', topic: 'General CBN Knowledge', questionText: 'Late submission of audited annual accounts by Finance Companies attracts a fine of:', options: ['₦1,000 for each day during which default occurs', '₦50,000 for each day during which default occurs', '₦7,000 for each day during which default occurs', '₦5,000 for each day during which default occurs'], correctAnswer: '₦50,000 for each day during which default occurs' },
    { 
        id: 'q151', 
        departmentId: 'general', 
        topic: 'General CBN Knowledge', 
        questionText: 'Service transition contains detailed descriptions of which processes?', 
        options: [
            'Change management, service asset and configuration management, release and deployment management',
            'Service level management, service portfolio management, service asset and configuration management',
            'Service asset and configuration management, release and deployment management, request fulfillment',
            'Service level management, event management, service asset and configuration management'
        ], 
        correctAnswer: 'Change management, service asset and configuration management, release and deployment management' 
    },
    { 
        id: 'q152', 
        departmentId: 'general', 
        topic: 'General CBN Knowledge', 
        questionText: 'Limit, respectively for a mobile money Tier 2 wallet (Daily Cumulative Transaction Limit and Cumulative Balance Limit):', 
        options: [
            'N250,000 and N390,000',
            'N50,000 and N350,000',
            'N200,000 and N500,000',
            'N500,000 and Unlimited'
        ], 
        correctAnswer: 'N200,000 and N500,000' 
    },
    { 
        id: 'q153', 
        departmentId: 'general', 
        topic: 'General CBN Knowledge', 
        questionText: 'The primary purpose of the audit trail is to:', 
        options: [
            'Improve response time for users',
            'Establish accountability and responsibility for processed transactions',
            'Improve the operational efficiency of the system',
            'Provide useful information to auditors who may wish to track transactions'
        ], 
        correctAnswer: 'Establish accountability and responsibility for processed transactions' 
    },
];

export const mockExamHistory: ExamAttempt[] = [
    { id: 'att1', userId: '2', departmentId: 'bsd_fss', score: 2, totalQuestions: 3, date: '2024-05-10' },
    { id: 'att2', userId: '2', departmentId: 'bsd_fss', score: 1, totalQuestions: 3, date: '2024-05-15' },
    { id: 'att3', userId: '2', departmentId: 'rd', score: 1, totalQuestions: 2, date: '2024-05-20' },
    { id: 'att4', userId: '2', departmentId: 'bsd_fss', score: 3, totalQuestions: 3, date: '2024-06-01' },
];